usdot-fhwa-stol/carma-ssc-interface-wrapper

ssc_interface_wrapper/CMakeLists.txt
ssc_interface_wrapper/config/parameters.yaml
ssc_interface_wrapper/include/ssc_interface_wrapper.h
ssc_interface_wrapper/include/ssc_interface_wrapper_worker.h
ssc_interface_wrapper/launch/ssc_interface_wrapper.launch
ssc_interface_wrapper/package.xml
ssc_interface_wrapper/src/main.cpp
ssc_interface_wrapper/src/ssc_interface_wrapper.cpp
ssc_interface_wrapper/src/ssc_interface_wrapper_worker.cpp
ssc_interface_wrapper/test/test_ssc_interface_wrapper.cpp

Code built locally and all unit test passed.

Initial Wrapper Commit

---

ssc_interface_wrapper/src/ssc_interface_wrapper.cpp

Update driver type in DriverStatus messages to match carma3 spec

Update driver type for carma3

---

ssc_interface_wrapper/launch/ssc_pacmod_driver.launch

Fixes the remappings in the driver launch file

Fix topic remappings in ssc driver launch file

---

ssc_interface_wrapper/launch/carma_speed_steering_control.launch
ssc_interface_wrapper/launch/ssc_pacmod_driver.launch

This adds a launch file for launching the SSC in a remappable way to this repo. This has been regression tested on the vehicle.

Add ssc launch file to repo

---

.circleci/config.yml
.sonarqube/sonar-scanner.properties
docker/checkout.sh
ssc_interface_wrapper/test/test_ssc_interface_wrapper.cpp

This PR adds support for CI on this repo and resolves issue #15 by updating unit tests to match new message specs.

Add support for CI and fix unit tests for ssc_interface_wrapper

---

.circleci/config.yml
Dockerfile

Update base image version for new component release

Update base image version to autoware.ai:3.2.0

---

docs/pull_request_template.md

Adding CARMAPlatform PR template to this repo. Followed this documentation from github: https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

adding PR template

---

docker/checkout.sh
ssc_ds_fusion/package.xml
ssc_gear_change/package.xml
ssc_ne_pacifica/package.xml
ssc_pm_cascadia/package.xml
ssc_pm_lexus/package.xml

Updated package.xml, docker, circle, and checkout.sh with new versions for the release.

CARMASscInterfaceWrapper_2.2.0 Component release

---

.circleci/config.yml
Dockerfile
ssc_ds_fusion/package.xml
ssc_gear_change/package.xml
ssc_interface_wrapper/package.xml
ssc_ne_pacifica/package.xml
ssc_pm_cascadia/package.xml
ssc_pm_lexus/package.xml
ssc_tester/package.xml

Update base docker image version to 3.6.0 
Supports resolution of usdot-fhwa-stol/CARMAPlatform#333

Update autoware.ai base docker image to version 3.6.0

---

.circleci/config.yml
Dockerfile
docker/checkout.sh
ssc_ds_fusion/package.xml
ssc_gear_change/package.xml
ssc_interface_wrapper/package.xml
ssc_ne_pacifica/package.xml
ssc_pm_cascadia/package.xml
ssc_pm_lexus/package.xml
ssc_tester/package.xml

Component release of this repo for Urus
Supports usdot-fhwa-stol/CARMAPlatform#333

CARMASscInterfaceWrapper_2.3.0 Component release

---

.circleci/config.yml
.sonarqube/sonar-scanner.properties
docker/checkout.sh

PR for CARMASscInterfaceWrapper 2.4.0 release
Release needed in order to get updated CARMAMsgs version onto master so that a new docker image can be pushed to Docker Hub

Release/carma ssc interface wrapper 2.4.0

---

.circleci/config.yml
docker/build-image.sh
docker/checkout.sh
hooks/pre_build

Added a -d option to the build-image.sh script to allow builds to be tagged for our new usdotfhwastoltest Docker Hub org

added develop option to build-image.sh

---

docker/system_release.sh

Adding system_release.sh script to automate system release related dependency changes
none
Change should speed up system release process.
Change tested by running script and confirming sed and git commands worked as expected

adding system_release.sh

---

ssc_ds_fusion/package.xml
ssc_gear_change/package.xml
ssc_interface_wrapper/package.xml
ssc_ne_pacifica/package.xml
ssc_pm_cascadia/package.xml
ssc_pm_lexus/package.xml
ssc_tester/package.xml

PR for updating package.xml files.
Changed package.xml files for every package in this repository to format 3.
This change is required to move carma to newer software.
This has been tested by successfully building this repository.

Updated package.xml files PR

---

ssc_interface_wrapper/launch/ssc_ne_pacifica_driver.launch
ssc_interface_wrapper/launch/ssc_pacmod_driver.launch

Moves pacmod calibrations to the calibration repo. They are ported as a launch file due to the deep nature of the launch tree before they become ros arguments making a yaml file difficult to setup or maintain.
Supports 
https://github.com/usdot-fhwa-stol/carma-platform/issues/350
This is needed because kvaser devices have unique ids
Blue lexus shown to be working with this change

Move controller calibration files to calibration repo

---

ssc_interface_wrapper/launch/ssc_pm_cascadia_driver.launch

Moves pacmod calibrations for the trucks to the calibration repo. They are ported as a launch file due to the deep nature of the launch tree before they become ros arguments making a yaml file difficult to setup or maintain.
Supports 
https://github.com/usdot-fhwa-stol/carma-platform/issues/350
Resolve above issue
This is needed because kvaser devices have unique ids
Silver truck shown to be working with this change

Update freightliner pacmod launch file

---

.circleci/config.yml
Dockerfile
docker/checkout.bash
docker/install.sh
ssc_interface_wrapper/CMakeLists.txt
ssc_interface_wrapper/include/ssc_interface_wrapper.h

* Updated package.xml files
* built with colcon
* Update docker and header
* Fix docker file since install tag is now in new eagle master
Co-authored-by: Jerry Sun <Jerry.Sun@leidos.com>
Co-authored-by: Michael McConnell <Michael.McConnell-2@leidos.com>

Feature/building with colcon (#75)

---

.circleci/config.yml
Dockerfile
docker/build-image.sh
docker/checkout.bash
hooks/build
hooks/pre_build

This PR is to merge the changes from release 3.4.3 back into the develop branch. Also retargets base branches at develop
This is needed to keep the develop branch as a working version of our released master branch.
Has been tested as part of the Wanderer testing process.

Feature/sync 3.4.3

---

.circleci/config.yml
Dockerfile
docker/checkout.bash

Follow up of https://github.com/usdot-fhwa-stol/carma-ssc-interface-wrapper/pull/90 with version number changes for develop

Update build versions for develop after master sync

---

ssc_interface_wrapper/launch/carma_speed_steering_control.launch

Fix SSC launch issue as comment is before XML declaration tag.

Move comment in SSC to after XML declaration

---

ssc_tester/src/ssc_tester/ssc_tester_node.py

Port scripts to Python 3.
Part of the port of the CARMA code to ROS Noetic.
Test compiled script with "python3 -m py_compile <filename>"

Update scripts for Python 3

---

ssc_interface_wrapper/launch/carma_speed_steering_control.launch

Same as the PR on develop, fixes the XML type document declaration location.

Fix launch file XML decl location

---

hooks/pre_build
ssc_interface_wrapper/launch/carma_speed_steering_control.launch

Sync noetic/develop with release 3.7.0

Feature/sync noetic with 3.7.0

---

.circleci/config.yml
Dockerfile
docker/checkout.bash

This PR is to sync up develop with Release 3.7.0

Sync develop with 3.7

---

docker/checkout.bash

This PR resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1477 by adding the missing dependencies to the docker image for this repo. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1477
Functioning noetic release of carma-platform
This was successfully tested on the silver lexus. The vehicle is able to drive autonomously. 

Add missing deps to checkout.bash

---

hooks/build

This PR is to update hooks with secret keys for docker hub build

build hook: add secrets

---

hooks/build

build hook: fix whitespace

---

docker/install.sh

This PR removes installation call for pacmod-msgs which is a non-existent debian package in ros-foxy.
https://github.com/usdot-fhwa-stol/carma-ssc-interface-wrapper/issues/154
Image built local

remove ros-foxy-pacmod-msgs from install script

---

docker/checkout.bash

Dockerhub build failed because of this
https://hub.docker.com/repository/registry-1.docker.io/usdotfhwastolcandidate/carma-ssc-interface-wrapper/builds/20181528-9d4c-4cd2-9f16-442ed3edec73

Fix checkout script that stops automatic docker hub building

---

docker/install.sh

Updating image to not install pacmod3_msgs since they are being installed in carma-base under https://github.com/usdot-fhwa-stol/carma-base/pull/208
Removes installation for  pacmod3_msgs and apt-transport-s3 packages which

remove installation for unrequired packages

---

.github/workflows/README.md
.github/workflows/dockerhub-humble.yml
.github/workflows/dockerhub-noetic.yml

try fix the ci

---

ssc_interface_wrapper/launch/ssc_ds_fusion_driver.launch
ssc_interface_wrapper/launch/ssc_interface_wrapper.launch
ssc_interface_wrapper/launch/ssc_ne_pacifica_driver.launch
ssc_interface_wrapper/launch/ssc_pacmod_driver.launch
ssc_interface_wrapper/launch/ssc_pm_cascadia_dot_10002_driver.launch
ssc_interface_wrapper/launch/ssc_pm_cascadia_dot_10003_driver.launch
ssc_interface_wrapper/launch/ssc_pm_cascadia_dot_10004_driver.launch
ssc_interface_wrapper/launch/ssc_pm_cascadia_dot_80550_driver.launch

Supports removal of carma_record from carma-platform so we only run ROS2 humble platform.
Therefore, the recorder node is moved here which is the only node that is in ROS1.
Supports: https://github.com/usdot-fhwa-stol/carma-utils/pull/242
NA
ARC-175
ROS2 Humble Migration System Launch Test
Tested on SIM PC (launch is same with ssc)

Add carma_record launch

---

humble/Dockerfile

Updates ros2 docker build to not remove required dependencies in final image.

update ros2 docker build

---

ssc_interface_wrapper_ros2/launch/carma_speed_steering_control.launch.py
ssc_interface_wrapper_ros2/launch/remapped_ssc_interface.launch.py

This PR remaps topics used by the CARMA Web UI to match the topics used on the other vehicles. This enables the throttle, brake, and steering visualization to work on all vehicles.
Related PR: https://github.com/usdot-fhwa-stol/carma-web-ui/pull/179
[CAR-6113](https://usdot-carma.atlassian.net/browse/CAR-6113)
Needed to have the visualization for throttle, brake, and steering to work on the Blue Lexus.
Tested on the blue Lexus
[CAR-6113]: https://usdot-carma.atlassian.net/browse/CAR-6113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Car 6113 Lexus UI Fixes
